# fly.toml app configuration file generated for mdshack-ogapi on 2025-03-08T14:45:33-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mdshack-ogapi'
primary_region = 'atl'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
